{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Values.servicemonitor.namespace }}
  name: {{ include "api-chart.fullname" . }}-servicemonitor
  labels:
    release: prometheus-operator
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      release: prometheus-operator
      {{- include "api-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.servicemonitor.interval }}
      path: {{ .Values.servicemonitor.path }}
{{- end }}
