apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
